spring.datasource.url=jdbc:sqlserver://localhost:${DB_PORT:1433};databaseName=v2_gestao_seguranca;encrypt=true;trustServerCertificate=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.SQL=DEBUG
